-- Daily Task Board — Supabase schema
-- Run this once in your Supabase project: Dashboard → SQL Editor → New query → paste → Run.

-- Tasks table. `id` is generated by the client so the same task has the same id
-- whether it lives in localStorage or in the database (clean offline → online sync).
create table if not exists public.tasks (
  id          text primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  day         date not null,
  status      text not null check (status in ('todo', 'inProgress', 'done')),
  position    double precision not null default 0,
  title       text not null default '',
  notes       text not null default '',
  due         date,
  priority    text check (priority in ('low', 'medium', 'high')),
  label       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists tasks_user_day_idx on public.tasks (user_id, day);

-- Row-Level Security: every user can only see and change their own rows.
alter table public.tasks enable row level security;

drop policy if exists "Users manage their own tasks" on public.tasks;
create policy "Users manage their own tasks"
  on public.tasks
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Let other devices hear about changes in real time.
alter publication supabase_realtime add table public.tasks;
